version: '3'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=dan
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=somedb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
